name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image (amd64)
      run: docker build . --file Dockerfile --tag docker-z-way:$(date +%s)
    
    - name: Build the Docker image (armhf)
      run: docker build . --file Dockerfile.armhf --tag docker-z-way-armhf:$(date +%s)
    
    - name: Build the Docker image (aarch64)
      run: docker build . --file Dockerfile.aarch64 --tag docker-z-way-aarch64:$(date +%s)
