name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Build the Docker image (amd64)
      run: |
        docker build . --file Dockerfile --tag docker-z-way
        docker run --rm docker-z-way cat /etc/z-way/VERSION > image_version.txt
        
    - name: Set image tag (amd64)
      run: |
        IMAGE_VERSION=$(cat image_version.txt)
        docker tag docker-z-way docker-z-way:$IMAGE_VERSION-amd64
        echo "::set-output name=image_tag_amd64::docker-z-way:$IMAGE_VERSION-amd64"
        
    - name: Build the Docker image (armhf)
      run: |
        docker build . --file Dockerfile.armhf --tag docker-z-way-armhf
        docker run --rm docker-z-way-armhf cat /etc/z-way/VERSION > image_version_armhf.txt
        
    - name: Set image tag (armhf)
      run: |
        IMAGE_VERSION_ARMHF=$(cat image_version_armhf.txt)
        docker tag docker-z-way-armhf docker-z-way-armhf:$IMAGE_VERSION_ARMHF-armhf
        echo "::set-output name=image_tag_armhf::docker-z-way-armhf:$IMAGE_VERSION_ARMHF-armhf"
        
    - name: Build the Docker image (aarch64)
      run: |
        docker build . --file Dockerfile.aarch64 --tag docker-z-way-aarch64
        docker run --rm docker-z-way-aarch64 cat /etc/z-way/VERSION > image_version_aarch64.txt
        
    - name: Set image tag (aarch64)
      run: |
        IMAGE_VERSION_AARCH64=$(cat image_version_aarch64.txt)
        docker tag docker-z-way-aarch64 docker-z-way-aarch64:$IMAGE_VERSION_AARCH64-aarch64
        echo "::set-output name=image_tag_aarch64::docker-z-way-aarch64:$IMAGE_VERSION_AARCH64-aarch64"
        
    - name: Use Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Build and push Docker images
      run: |
        docker buildx build --platform linux/amd64,linux/arm/v7,linux/arm64/v8 --push --tag ${{ steps.image_tag_amd64.outputs.image_tag_amd64 }} --tag ${{ steps.image_tag_armhf.outputs.image_tag_armhf }} --tag ${{ steps.image_tag_aarch64.outputs.image_tag_aarch64 }} .
